#ifndef QGOOGLESPEECH_GLOBAL_H
#define QGOOGLESPEECH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QGOOGLESPEECH_LIBRARY)
#  define QGOOGLESPEECHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QGOOGLESPEECHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QGOOGLESPEECH_GLOBAL_H
